on: push
name: ğŸš€ Deploy no push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Pegar o cÃ³digo
      uses: actions/checkout@v3
    
    - name: ğŸ“‚ Sincronizando ...
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 15.229.86.2
        username: admin
        password: admin
