on: push
name: ğŸš€ Deploy no push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Pegar o cÃ³digo
      uses: actions/checkout@v3
    
    - name: ğŸ“‚ Sincronizando ...
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: 15.229.86.2
        user: admin
        password: admin
